import Config

# Force using SSL in production. This also sets the "strict-security-transport" header,
# also known as HSTS. `:force_ssl` is required to be set at compile-time.
config :blog_web, BlogWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :blog_web, BlogWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :logger, level: :info
